### ISSUE TITLE
Second Sentry plugin

### ISSUE THREAD

**Issue by rostockahoi** [born05/craft-sentry#1]
Hi, could you please explain why you published a second Sentry plugin which is based on the first one by Luke?

**Comment by roelvanhintum** [comment]
@rostockahoi his plugin wasn’t updated for 9 months. Originally i created a pull-request with updates. I got no responses for a long time. After someone else asked me to turn that pull-request into a separate plugin i decided to rewrite it with cleaner config options. This one uses the sentry sdk instead of raven. 
See:
https://github.com/lukeyouell/craft-sentry/pull/22

**Comment by rostockahoi** [comment]
Ah I see. Then, thanks a lot for this :+1:
