### ISSUE TITLE
Updating from 2.0.1 to 3.0.0 leads to "missing clientKey" error

### ISSUE THREAD

**Issue by Mixxey** [born05/craft-sentry#33]
Hi everyone,

I don't know if this is a bug or if I'm doing something wrong, but this is what happens:

I ran CMS updates for my Craft 4 installation and updated Sentry SDK from version 2.0.1 to the lates 3.0.0. Now whenever I try to display an entry, I see the following error message:

"Failed to register Sentry browser client due to missing clientKey"

![image](https://github.com/born05/craft-sentry/assets/71216279/dec69f24-0fa1-43cf-8c6c-0621ffd1b240)

Adding "clientKey" to /config/sentry-sdk.php and setting it to an empty string seems to help, as it removes the error while errors still get logged to sentry. But since I'm not quite sure if this is a valid solution, I'm posting here anyway, hoping for some advice.

Many thanks in advance :)

Best regards,
Tina

**Comment by roelvanhintum** [comment]
@Mixxey, it looks like you have `reportJsErrors` enabled, maybe by accident, which requires the `clientKey` to function. Setting `reportJsErrors` to `false` should solve this, if you don't want sentry to load in the browser. This is because of the latest javascript version: https://docs.sentry.io/platforms/javascript/

**Comment by Mixxey** [comment]
Thanks a lot for getting back :) That helped, and I found and fixed another problem on my side. Everything works fine now :)
